### ISSUE TITLE
Getting egg_info error when installing with pip 

### ISSUE THREAD

**Issue by dave-cryptoai** [Dirrot/python-cryptocoincharts-api#6]
I get an egg_info error when trying 'pip install CryptoCoinChartsApi'

Here's the error
http://pastebin.com/XHjRFdra

**Comment by Dirrot** [comment]
Your pastebin file says, that you called the 'pip3 install CryptoCoinChartsApi' command, which uses the interpreter for python3. So i guess you have python3 installed.

In the setup.py script, especially the first line, you see that this script should be interpreted with python2.

[StackOverflow-Hint](http://stackoverflow.com/questions/2429511/why-do-people-write-usr-bin-env-python-on-the-first-line-of-a-python-script)
